// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountForm: typeof import('./src/components/AccountForm.vue')['default']
    AdminNavMenu: typeof import('./src/components/NavMenu/AdminNavMenu.vue')['default']
    AppCard: typeof import('./src/components/AppCard.vue')['default']
    BookCard: typeof import('./src/components/Document/BookCard.vue')['default']
    ConferenceCard: typeof import('./src/components/Document/ConferenceCard.vue')['default']
    DocumentItem: typeof import('./src/components/Document/DocumentItem.vue')['default']
    DocumentList: typeof import('./src/components/Document/DocumentList.vue')['default']
    FeatureItem: typeof import('./src/components/FeatureList/FeatureItem.vue')['default']
    FeatureList: typeof import('./src/components/FeatureList/FeatureList.vue')['default']
    JournalCard: typeof import('./src/components/Document/JournalCard.vue')['default']
    LoadMoreHint: typeof import('./src/components/LoadMoreHint.vue')['default']
    ReaderOperation: typeof import('./src/components/ReaderAdmin/ReaderOperation.vue')['default']
    ReaderOperations: typeof import('./src/components/ReaderAdmin/ReaderOperations.vue')['default']
    ReaderTable: typeof import('./src/components/ReaderAdmin/ReaderTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./src/components/SearchBox.vue')['default']
    TAvatar: typeof import('tdesign-vue-next')['Avatar']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCheckbox: typeof import('tdesign-vue-next')['Checkbox']
    TCol: typeof import('tdesign-vue-next')['Col']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    TImage: typeof import('tdesign-vue-next')['Image']
    TInput: typeof import('tdesign-vue-next')['Input']
    TInputAdornment: typeof import('tdesign-vue-next')['InputAdornment']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TRow: typeof import('tdesign-vue-next')['Row']
    TTable: typeof import('tdesign-vue-next')['Table']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
    UserNavMenu: typeof import('./src/components/NavMenu/UserNavMenu.vue')['default']
  }
}
